### ISSUE TITLE
Python3 version

### ISSUE THREAD

**Issue by makavakam** [ptresearch/mmdetect#1]
Hi PT Team,

Here is Python3 version of your script:

https://github.com/makavakam/mmdetect

I'm sorry if it's an incorrect way of delivering the code I'm just new to GitHub. But I suppose it can be useful now.

Best regards,
AM

**Comment by ptresearch** [comment]
Thank you! Pull request is a correct way of delivering the code. Python3 support has been added at https://github.com/ptresearch/mmdetect/commit/725b40249848dce297598db4a41dcf2fb8ea6394
