### ISSUE TITLE
hex vs decimal parsing me_fwsts1

### ISSUE THREAD

**Issue by leighklotz** [ptresearch/mmdetect#4]
In this line I get an error because val="6a"

https://github.com/ptresearch/mmdetect/blob/master/mmdetect.py#L58

The code assumes this value is a decimal string, but in the one case I've tried, it's not.
Machine details available on request.

**Comment by h0t** [comment]
Thank you! Fixed in https://github.com/ptresearch/mmdetect/commit/4369dc559cf0dc6256f7393b7c7644f47c9eef45

**Comment by h0t** [comment]
@leighklotz could you give me please you machine details?

**Comment by leighklotz** [comment]
no longer fails with fix
